-- UnauthCustomer
insert into UnauthCustomer (oid, customerid, customertype, typedcustomeroid, bankcustomerid, mnemonic, applicant, sector, target, cbscustomerstatus, nationality, residence, language, introducerbankaccountno, introducercustomerid, isintroduceragent, enrollmenttype, ecopurposecode, cbsectorcode, cbindustrycode, customerqrcode, cbsfailurereason, agentoid, servicepointoid, serviceterminaloid, bankoid, branchoid, agentstaffoid, traceid, currentversion, cbscurrentversion, status, editcommit, lockedby, lockedon, editedby, editedon, approvedby, approvedon, remarkedby, remarkedon, isapproverremarks, approverremarks, isnewrecord, applicationdate, createdby, createdon, bankcustomeridcreateref, bankcustomeridcreateon, bankcustomeridupdateref, bankcustomeridupdateon, dataupdatedby, dataupdatedon, dataupdateapprovedby, dataupdateapprovedon, bankapprovedby, bankapprovedon, bankapprovalauthorizedby, bankapprovalauthorizedon, activatedby, activatedon, applicationrejectedby, applicationrejectedon, applicationrejectionreason, closedby, closedon, closingremark, deletedby, deletedon, deletionremark) values ('4876655','D4876655D','[{"order":1,"personOid":"9663275","position":"null"}]','1000','1','BD','BD','1','ApplicationSubmitted');
insert into UnauthCustomer (oid, customerid, customertype, typedcustomeroid, bankcustomerid, mnemonic, applicant, sector, target, cbscustomerstatus, nationality, residence, language, introducerbankaccountno, introducercustomerid, isintroduceragent, enrollmenttype, ecopurposecode, cbsectorcode, cbindustrycode, customerqrcode, cbsfailurereason, agentoid, servicepointoid, serviceterminaloid, bankoid, branchoid, agentstaffoid, traceid, currentversion, cbscurrentversion, status, editcommit, lockedby, lockedon, editedby, editedon, approvedby, approvedon, remarkedby, remarkedon, isapproverremarks, approverremarks, isnewrecord, applicationdate, createdby, createdon, bankcustomeridcreateref, bankcustomeridcreateon, bankcustomeridupdateref, bankcustomeridupdateon, dataupdatedby, dataupdatedon, dataupdateapprovedby, dataupdateapprovedon, bankapprovedby, bankapprovedon, bankapprovalauthorizedby, bankapprovalauthorizedon, activatedby, activatedon, applicationrejectedby, applicationrejectedon, applicationrejectionreason, closedby, closedon, closingremark, deletedby, deletedon, deletionremark) values ('000003145','D000003145','HENA BIBI',null,null,null,null,null,'BankApproved');
commit;

-- Customer
insert into Customer (oid, customerid, bankcustomerid, mnemonic, applicant, typedcustomeroid, ecopurposecode, language, nationality, cbsectorcode, cbindustrycode, residence, sector, target, dataupdateapprovedby, dataupdateapprovedon, customertype, enrollmenttype, introducerbankaccountno, introducercustomerid, isintroduceragent, cbscustomerstatus, cbsfailurereason, agentoid, servicepointoid, serviceterminaloid, bankoid, branchoid, traceid, currentversion, cbscurrentversion, status, editedby, editedon, approvedby, approvedon, remarkedby, remarkedon, isapproverremarks, approverremarks, isnewrecord, applicationdate, createdby, createdon, bankcustomeridcreateref, bankcustomeridcreateon, bankcustomeridupdateref, bankcustomeridupdateon, dataupdatedby, dataupdatedon, bankapprovalauthorizedby, bankapprovalauthorizedon, bankapprovedby, bankapprovedon, activatedby, activatedon, applicationrejectedby, applicationrejectedon, applicationrejectionreason, closedby, closedon, closingremark, deletedby, deletedon, deletionremark, customerqrcode, agentstaffoid) values ('2395771','D2395771D','[{"order":1,"personOid":"9777783","position":"INDIVIDUAL"}]','1','BD','BD','1000','1','Active');
insert into Customer (oid, customerid, bankcustomerid, mnemonic, applicant, typedcustomeroid, ecopurposecode, language, nationality, cbsectorcode, cbindustrycode, residence, sector, target, dataupdateapprovedby, dataupdateapprovedon, customertype, enrollmenttype, introducerbankaccountno, introducercustomerid, isintroduceragent, cbscustomerstatus, cbsfailurereason, agentoid, servicepointoid, serviceterminaloid, bankoid, branchoid, traceid, currentversion, cbscurrentversion, status, editedby, editedon, approvedby, approvedon, remarkedby, remarkedon, isapproverremarks, approverremarks, isnewrecord, applicationdate, createdby, createdon, bankcustomeridcreateref, bankcustomeridcreateon, bankcustomeridupdateref, bankcustomeridupdateon, dataupdatedby, dataupdatedon, bankapprovalauthorizedby, bankapprovalauthorizedon, bankapprovedby, bankapprovedon, activatedby, activatedon, applicationrejectedby, applicationrejectedon, applicationrejectionreason, closedby, closedon, closingremark, deletedby, deletedon, deletionremark, customerqrcode, agentstaffoid) values ('4876655','D4876655D','[{"order":1,"personOid":"9663275","position":"null"}]','1','BD','BD','1000','1','ApplicationSubmitted');
insert into Customer (oid, customerid, bankcustomerid, mnemonic, applicant, typedcustomeroid, ecopurposecode, language, nationality, cbsectorcode, cbindustrycode, residence, sector, target, dataupdateapprovedby, dataupdateapprovedon, customertype, enrollmenttype, introducerbankaccountno, introducercustomerid, isintroduceragent, cbscustomerstatus, cbsfailurereason, agentoid, servicepointoid, serviceterminaloid, bankoid, branchoid, traceid, currentversion, cbscurrentversion, status, editedby, editedon, approvedby, approvedon, remarkedby, remarkedon, isapproverremarks, approverremarks, isnewrecord, applicationdate, createdby, createdon, bankcustomeridcreateref, bankcustomeridcreateon, bankcustomeridupdateref, bankcustomeridupdateon, dataupdatedby, dataupdatedon, bankapprovalauthorizedby, bankapprovalauthorizedon, bankapprovedby, bankapprovedon, activatedby, activatedon, applicationrejectedby, applicationrejectedon, applicationrejectionreason, closedby, closedon, closingremark, deletedby, deletedon, deletionremark, customerqrcode, agentstaffoid) values ('7680073','D7680073D','[{"order":1,"personOid":"8845626","position":"null"}]','1','BD','BD','1000','1','ApplicationSubmitted');
insert into Customer (oid, customerid, bankcustomerid, mnemonic, applicant, typedcustomeroid, ecopurposecode, language, nationality, cbsectorcode, cbindustrycode, residence, sector, target, dataupdateapprovedby, dataupdateapprovedon, customertype, enrollmenttype, introducerbankaccountno, introducercustomerid, isintroduceragent, cbscustomerstatus, cbsfailurereason, agentoid, servicepointoid, serviceterminaloid, bankoid, branchoid, traceid, currentversion, cbscurrentversion, status, editedby, editedon, approvedby, approvedon, remarkedby, remarkedon, isapproverremarks, approverremarks, isnewrecord, applicationdate, createdby, createdon, bankcustomeridcreateref, bankcustomeridcreateon, bankcustomeridupdateref, bankcustomeridupdateon, dataupdatedby, dataupdatedon, bankapprovalauthorizedby, bankapprovalauthorizedon, bankapprovedby, bankapprovedon, activatedby, activatedon, applicationrejectedby, applicationrejectedon, applicationrejectionreason, closedby, closedon, closingremark, deletedby, deletedon, deletionremark, customerqrcode, agentstaffoid) values ('000003145','D000003145','HENA BIBI',null,null,null,null,null,'Active');
insert into Customer (oid, customerid, bankcustomerid, mnemonic, applicant, typedcustomeroid, ecopurposecode, language, nationality, cbsectorcode, cbindustrycode, residence, sector, target, dataupdateapprovedby, dataupdateapprovedon, customertype, enrollmenttype, introducerbankaccountno, introducercustomerid, isintroduceragent, cbscustomerstatus, cbsfailurereason, agentoid, servicepointoid, serviceterminaloid, bankoid, branchoid, traceid, currentversion, cbscurrentversion, status, editedby, editedon, approvedby, approvedon, remarkedby, remarkedon, isapproverremarks, approverremarks, isnewrecord, applicationdate, createdby, createdon, bankcustomeridcreateref, bankcustomeridcreateon, bankcustomeridupdateref, bankcustomeridupdateon, dataupdatedby, dataupdatedon, bankapprovalauthorizedby, bankapprovalauthorizedon, bankapprovedby, bankapprovedon, activatedby, activatedon, applicationrejectedby, applicationrejectedon, applicationrejectionreason, closedby, closedon, closingremark, deletedby, deletedon, deletionremark, customerqrcode, agentstaffoid) values ('6845560','D6845560D','[{"order":1,"personOid":"5625683","position":"INDIVIDUAL"}]','1','BD','BD','1000','1','Active');
insert into Customer (oid, customerid, bankcustomerid, mnemonic, applicant, typedcustomeroid, ecopurposecode, language, nationality, cbsectorcode, cbindustrycode, residence, sector, target, dataupdateapprovedby, dataupdateapprovedon, customertype, enrollmenttype, introducerbankaccountno, introducercustomerid, isintroduceragent, cbscustomerstatus, cbsfailurereason, agentoid, servicepointoid, serviceterminaloid, bankoid, branchoid, traceid, currentversion, cbscurrentversion, status, editedby, editedon, approvedby, approvedon, remarkedby, remarkedon, isapproverremarks, approverremarks, isnewrecord, applicationdate, createdby, createdon, bankcustomeridcreateref, bankcustomeridcreateon, bankcustomeridupdateref, bankcustomeridupdateon, dataupdatedby, dataupdatedon, bankapprovalauthorizedby, bankapprovalauthorizedon, bankapprovedby, bankapprovedon, activatedby, activatedon, applicationrejectedby, applicationrejectedon, applicationrejectionreason, closedby, closedon, closingremark, deletedby, deletedon, deletionremark, customerqrcode, agentstaffoid) values ('000001441','D000001441','MD.  MAJNU  ALAM',null,null,null,null,null,'Active');
commit;

-- CustomerPerson
insert into CustomerPerson (oid, customeroid, personoid) values ('000001441');
commit;


