-- Count query
select 'absdata.AuditLog' as tableName, count(*) from absdata.AuditLog union all
select 'public.AuditLog' as tableName, count(*) from public.AuditLog union all
select 'absdata.Role' as tableName, count(*) from absdata.Role union all
select 'public.Role' as tableName, count(*) from public.role union all
select 'absdata.topmenu' as tableName, count(*) from absdata.topmenu union all
select 'public.topmenu' as tableName, count(*) from public.topmenu union all
select 'absdata.leftmenu' as tableName, count(*) from absdata.leftmenu union all
select 'public.leftmenu' as tableName, count(*) from public.leftmenu union all
select 'absdata.LoginTrail' as tableName, count(*) from absdata.LoginTrail union all
select 'public.LoginTrail' as tableName, count(*) from public.LoginTrail union all
select 'absdata.login' as tableName, count(*) from absdata.login union all
select 'public.login' as tableName, count(*) from public.login union all
select 'absdata.GlMasterData' as tableName, count(*) from absdata.GlMasterData union all
select 'public.GlMasterData' as tableName, count(*) from public.GlMasterData union all
select 'absdata.TagDictionary' as tableName, count(*) from absdata.TagDictionary union all
select 'public.TagDictionary' as tableName, count(*) from public.TagDictionary union all
select 'absdata.TagLink' as tableName, count(*) from absdata.TagLink union all
select 'public.TagLink' as tableName, count(*) from public.TagLink union all
select 'absdata.TagLinkDraft' as tableName, count(*) from absdata.TagLinkDraft union all
select 'public.TagLinkDraft' as tableName, count(*) from public.TagLinkDraft union all
select 'absdata.product' as tableName, count(*) from absdata.product union all
select 'public.product' as tableName, count(*) from public.product union all
select 'absdata.MetaProperty' as tableName, count(*) from absdata.MetaProperty union all
select 'public.MetaProperty' as tableName, count(*) from public.MetaProperty union all
select 'absdata.DdlMetaData' as tableName, count(*) from absdata.DdlMetaData union all
select 'public.DdlMetaData' as tableName, count(*) from public.DdlMetaData union all
select 'absdata.GeoData' as tableName, count(*) from absdata.GeoData union all
select 'public.GeoData' as tableName, count(*) from public.GeoData union all
select 'absdata.Bank' as tableName, count(*) from absdata.Bank union all
select 'public.Bank' as tableName, count(*) from public.Bank union all
select 'absdata.Branch' as tableName, count(*) from absdata.Branch union all
select 'public.Branch' as tableName, count(*) from public.Branch union all
select 'absdata.Calendar' as tableName, count(*) from absdata.Calendar union all
select 'public.Calendar' as tableName, count(*) from public.Calendar union all
select 'absdata.CalendarDetails' as tableName, count(*) from absdata.CalendarDetails union all
select 'public.CalendarDetails' as tableName, count(*) from public.CalendarDetails union all
select 'absdata.SegmentDef' as tableName, count(*) from absdata.SegmentDef union all
select 'public.SegmentDef' as tableName, count(*) from public.SegmentDef union all
select 'absdata.SegmentItem' as tableName, count(*) from absdata.SegmentItem union all
select 'public.SegmentItem' as tableName, count(*) from public.SegmentItem union all
select 'absdata.ChargeModelDef' as tableName, count(*) from absdata.ChargeModelDef union all
select 'public.ChargeModelDef' as tableName, count(*) from public.ChargeModelDef union all
select 'absdata.ChargeModelItem' as tableName, count(*) from absdata.ChargeModelItem union all
select 'public.ChargeModelItem' as tableName, count(*) from public.ChargeModelItem union all
select 'absdata.PasswordPolicy' as tableName, count(*) from absdata.PasswordPolicy union all
select 'public.PasswordPolicy' as tableName, count(*) from public.PasswordPolicy union all
select 'absdata.PasswordHistory' as tableName, count(*) from absdata.PasswordHistory union all
select 'public.PasswordHistory' as tableName, count(*) from public.PasswordHistory union all
select 'absdata.AccountTransactionProfile' as tableName, count(*) from absdata.AccountTransactionProfile union all
select 'public.AccountTransactionProfile' as tableName, count(*) from public.AccountTransactionProfile union all
select 'absdata.OutletTransactionProfile' as tableName, count(*) from absdata.OutletTransactionProfile union all
select 'public.OutletTransactionProfile' as tableName, count(*) from public.OutletTransactionProfile union all
select 'absdata.ProductAccTransProfile' as tableName, count(*) from absdata.ProductAccTransProfile union all
select 'public.ProductAccTransProfile' as tableName, count(*) from public.ProductAccTransProfile union all
select 'absdata.DraftAgent' as tableName, count(*) from absdata.DraftAgent union all
select 'public.AgentDraft' as tableName, count(*) from public.AgentDraft union all
select 'absdata.Agent' as tableName, count(*) from absdata.Agent union all
select 'public.Agent' as tableName, count(*) from public.Agent union all
select 'absdata.AgentAccountDraft' as tableName, count(*) from absdata.AgentAccountDraft union all
select 'public.AgentAccountDraft' as tableName, count(*) from public.AgentAccountDraft union all
select 'absdata.AgentAccount' as tableName, count(*) from absdata.AgentAccount union all
select 'public.AgentAccount' as tableName, count(*) from public.AgentAccount union all
select 'absdata.DraftAgentServiceStaff' as tableName, count(*) from absdata.DraftAgentServiceStaff union all
select 'public.AgentServiceStaffDraft' as tableName, count(*) from public.AgentServiceStaffDraft union all
select 'absdata.AgentCategory' as tableName, count(*) from absdata.AgentCategory union all
select 'public.AgentCategory' as tableName, count(*) from public.AgentCategory union all
select 'absdata.OutletArea' as tableName, count(*) from absdata.OutletArea union all
select 'public.OutletArea' as tableName, count(*) from public.OutletArea union all
select 'absdata.OutletZone' as tableName, count(*) from absdata.OutletZone union all
select 'public.OutletZone' as tableName, count(*) from public.OutletZone union all
select 'absdata.DraftServicePoint' as tableName, count(*) from absdata.DraftServicePoint union all
select 'public.ServicePointDraft' as tableName, count(*) from public.ServicePointDraft union all
select 'absdata.ServicePoint' as tableName, count(*) from absdata.ServicePoint union all
select 'public.ServicePoint' as tableName, count(*) from public.ServicePoint union all
select 'absdata.FpDevice' as tableName, count(*) from absdata.FpDevice union all
select 'public.ServiceTerminal' as tableName, count(*) from public.ServiceTerminal union all
select 'absdata.ClientDevice' as tableName, count(*) from absdata.ClientDevice union all
select 'public.ServiceTerminal' as tableName, count(*) from public.ServiceTerminal union all
select 'absdata.PrinterDevice' as tableName, count(*) from absdata.PrinterDevice union all
select 'public.ServiceTerminal' as tableName, count(*) from public.ServiceTerminal union all
select 'absdata.CardDevice' as tableName, count(*) from absdata.CardDevice union all
select 'public.ServiceTerminal' as tableName, count(*) from public.ServiceTerminal union all
select 'absdata.ServiceTerminal' as tableName, count(*) from absdata.ServiceTerminal union all
select 'public.ServiceTerminal' as tableName, count(*) from public.ServiceTerminal union all
select 'absdata.AgentServiceStaff' as tableName, count(*) from absdata.AgentServiceStaff union all
select 'public.AgentServiceStaff' as tableName, count(*) from public.AgentServiceStaff union all
select 'absdata.person' as tableName, count(*) from absdata.person union all
select 'public.customer' as tableName, count(*) from public.customer union all
select 'absdata.customer' as tableName, count(*) from absdata.customer union all
select 'public.customer' as tableName, count(*) from public.customer union all
select 'absdata.Account' as tableName, count(*) from absdata.Account union all
select 'public.Account' as tableName, count(*) from public.Account union all
select 'absdata.CustomerAccount' as tableName, count(*) from absdata.CustomerAccount union all
select 'public.CustomerAccount' as tableName, count(*) from public.CustomerAccount union all
select 'absdata.CustomerQrCard' as tableName, count(*) from absdata.CustomerQrCard union all
select 'public.CustomerQrCard' as tableName, count(*) from public.CustomerQrCard union all
select 'absdata.PersonFingerprint' as tableName, count(*) from absdata.PersonFingerprint union all
select 'public.fingerprint' as tableName, count(*) from public.fingerprint union all
select 'absdata.personfingerprintlog' as tableName, count(*) from absdata.personfingerprintlog union all
select 'public.fingerprintlog' as tableName, count(*) from public.fingerprintlog union all
select 'absdata.SignatoryInfo' as tableName, count(*) from absdata.SignatoryInfo union all
select 'public.SignatoryInfo' as tableName, count(*) from public.SignatoryInfo union all
select 'absdata.AccountOperationInstruction' as tableName, count(*) from absdata.AccountOperationInstruction union all
select 'public.SignatoryInfo' as tableName, count(*) from public.SignatoryInfo union all
select 'absdata.FundTransferChargeModel' as tableName, count(*) from absdata.FundTransferChargeModel union all
select 'public.FundTransferChargeModel' as tableName, count(*) from public.FundTransferChargeModel union all
select 'absdata.BillType' as tableName, count(*) from absdata.BillType union all
select 'public.BillType' as tableName, count(*) from public.BillType union all
select 'absdata.UtilityCompany' as tableName, count(*) from absdata.UtilityCompany union all
select 'public.UtilityCompany' as tableName, count(*) from public.UtilityCompany union all
select 'absdata.CompanyZone' as tableName, count(*) from absdata.CompanyZone union all
select 'public.CompanyZone' as tableName, count(*) from public.CompanyZone union all
select 'absdata.ZoneAgent' as tableName, count(*) from absdata.ZoneAgent union all
select 'public.ZoneAgent' as tableName, count(*) from public.ZoneAgent union all
select 'absdata.ZoneBranch' as tableName, count(*) from absdata.ZoneBranch union all
select 'public.ZoneBranch' as tableName, count(*) from public.ZoneBranch union all
select 'absdata.BillCollection' as tableName, count(*) from absdata.BillCollection union all
select 'public.BillCollection' as tableName, count(*) from public.BillCollection union all
select 'absdata.RebChargeModel' as tableName, count(*) from absdata.RebChargeModel union all
select 'public.RebChargeModel' as tableName, count(*) from public.RebChargeModel union all
select 'absdata.GasBillCollection' as tableName, count(*) from absdata.GasBillCollection union all
select 'public.GasBillCollection' as tableName, count(*) from public.GasBillCollection union all
select 'absdata.GasJalalabadChargeModel' as tableName, count(*) from absdata.GasJalalabadChargeModel union all
select 'public.GasJalalabadChargeModel' as tableName, count(*) from public.GasJalalabadChargeModel union all
select 'absdata.ExchangeHouse' as tableName, count(*) from absdata.ExchangeHouse union all
select 'public.ExchangeHouse' as tableName, count(*) from public.ExchangeHouse union all
select 'absdata.Remittance' as tableName, count(*) from absdata.Remittance union all
select 'public.Remittance' as tableName, count(*) from public.Remittance;
