/*
This table associated to hold cusotmer appliance information
oid                                      : Primary key, generated by customerCode + applianceTypeCode
customerCode                             : Unique code to identify a customer, comes from BgdclCustomerBasicInfo
applianceTypeCode                        : Unique code to identify appliance type, comes from BgdclApplianceInfo table
quantity                                 : Numbere of appliance
user                                     : -
bgdclSchemaName                          : From which schema this data pick
*/
create table                             BgdclNmCustomerAppliance
(
oid                                      varchar(128)                                                not null,
customerCode                             varchar(15),
applianceTypeCode                        varchar(2),
quantity                                 int,
"user"                                     varchar(200),
bgdclSchemaName                          varchar(128),
constraint                               pk_BgdclNmCustomerAppliance                                 primary key    (oid)
);

/*
This table associated to hold cusotmer appliance information history
oid                                      : Primary key, generated by day + month + year + customerCode + applianceTypeCode
day                                      : updated day
month                                    : updated month
year                                     : updated year
customerCode                             : Unique code to identify a customer, comes from BgdclCustomerBasicInfo
applianceTypeCode                        : Unique code to identify appliance type, comes from BgdclApplianceInfo table
quantity                                 : Number of appliance
user                                     : -
bgdclSchemaName                          : From which schema this data pick
*/
create table                             BgdclNmCustApplianceHistory
(
oid                                      varchar(128)                                                not null,
day                                      int,
month                                    int,
year                                     int,
customerCode                             varchar(15),
applianceTypeCode                        varchar(2),
quantity                                 int,
"user"                                     varchar(200),
bgdclSchemaName                          varchar(128),
constraint                               pk_BgdclNmCustApplianceHistory                              primary key    (oid)
);

/*
This table associated to hold cusotmer basic information
customerCode                             : Primary Key, to identify a customer uniquely. Generated by areaCode + subAreaCode + customerTypeCode + - + six digits serial number 
salesSerial                              : -
revenueSerial                            : -
customerCodeOld                          : This code known by customer
customerTypeCode                         : Which type of customer, comes from BgdclCustomerType table
areaCode                                 : Code of a area, comes from BgdclAreaInfo table
subAreaCode                              : Code of a sub-area, comes from BgdclAreaInfo table
mid                                      : -
customerName                             : Name of a customer
fathersOrHusbandsName                    : Name of fathers or husbank
mothersName                              : Name of mother
installationAddressP1                    : Customer address
installationAddressP2                    : Customer address
installationAddressP3                    : Customer address
billingAddressP1                         : In which address bill will be send
billingAddressP2                         : In which address bill will be send
billingAddressP3                         : In which address bill will be send
telephoneNo                              : Customer telephone number
purposeOfUsage                           : In which purpose gas will be used
natureOfUsage                            : -
maxLoadPerHour                           : -
maxLoadPerPay                            : -
maxLoadPerMonth                          : -
minLoadPerMonth                          : -
securityDepositAmount                    : -
securityDepositAmount1                   : -
dateOfApplication                        : In which date apply for connection
dateOfContract                           : In which date contract done
dateOfConnection                         : In which date connection given
bankCode                                 : Code to third pary. Like Doer, South East Bank
connectionStatusId                       : -
vatValue                                 : -
customerImage                            : -
bulk                                     : -
zone                                     : -
customerCodePrev                         : -
customerType                             : wheather customer is metered or non-metered. Value  metered, non-metered
bgdclSchemaName                          : From which schema this data pick
*/
create table                             BgdclCustomerBasicInfo
(
customerCode                             varchar(15)                                                 not null,
salesSerial                              bigint,
revenueSerial                            bigint,
customerCodeOld                          varchar(50),
customerTypeCode                         char,
areaCode                                 char,
subAreaCode                              char,
mid                                      char,
customerName                             varchar(50),
fathersOrHusbandsName                    varchar(50),
mothersName                              varchar(50),
installationAddressP1                    varchar(100),
installationAddressP2                    varchar(100),
installationAddressP3                    varchar(50),
billingAddressP1                         varchar(100),
billingAddressP2                         varchar(100),
billingAddressP3                         varchar(50),
telephoneNo                              varchar(25),
purposeOfUsage                           varchar(30),
natureOfUsage                            varchar(30),
maxLoadPerHour                           numeric(14,2),
maxLoadPerPay                            numeric(14,2),
maxLoadPerMonth                          numeric(14,2),
minLoadPerMonth                          numeric(14,2),
securityDepositAmount                    numeric(14,2),
securityDepositAmount1                   numeric(14,2),
dateOfApplication                        date,
dateOfContract                           date,
dateOfConnection                         date,
bankCode                                 varchar(8),
connectionStatusId                       char,
vatValue                                 numeric(5,4),
customerImage                            text,
bulk                                     int,
zone                                     varchar(13),
customerCodePrev                         varchar(2),
customerType                             varchar(14),
bgdclSchemaName                          varchar(128),
constraint                               pk_BgdclCustomerBasicInfo                                   primary key    (customerCode),
constraint                               ck_customerType_BgdclCustomerBasicInfo                      check          (customerType = 'metered' or customerType = 'non-metered')
);


