-- Count query
select 'absnew.AuditLog' as tableName, count(*) from absnew.AuditLog union all
select 'absold.AuditLog' as tableName, count(*) from absold.AuditLog union all
select 'absnew.Role' as tableName, count(*) from absnew.Role union all
select 'absold.Role' as tableName, count(*) from absold.role union all
select 'absnew.topmenu' as tableName, count(*) from absnew.topmenu union all
select 'absold.topmenu' as tableName, count(*) from absold.topmenu union all
select 'absnew.leftmenu' as tableName, count(*) from absnew.leftmenu union all
select 'absold.leftmenu' as tableName, count(*) from absold.leftmenu union all
select 'absnew.LoginTrail' as tableName, count(*) from absnew.LoginTrail union all
select 'absold.LoginTrail' as tableName, count(*) from absold.LoginTrail union all
select 'absnew.login' as tableName, count(*) from absnew.login union all
select 'absold.login' as tableName, count(*) from absold.login union all
select 'absnew.GlMasterData' as tableName, count(*) from absnew.GlMasterData union all
select 'absold.GlMasterData' as tableName, count(*) from absold.GlMasterData union all
select 'absnew.TagDictionary' as tableName, count(*) from absnew.TagDictionary union all
select 'absold.TagDictionary' as tableName, count(*) from absold.TagDictionary union all
select 'absnew.TagLink' as tableName, count(*) from absnew.TagLink union all
select 'absold.TagLink' as tableName, count(*) from absold.TagLink union all
select 'absnew.TagLinkDraft' as tableName, count(*) from absnew.TagLinkDraft union all
select 'absold.TagLinkDraft' as tableName, count(*) from absold.TagLinkDraft union all
select 'absnew.product' as tableName, count(*) from absnew.product union all
select 'absold.product' as tableName, count(*) from absold.product union all
select 'absnew.MetaProperty' as tableName, count(*) from absnew.MetaProperty union all
select 'absold.MetaProperty' as tableName, count(*) from absold.MetaProperty union all
select 'absnew.DdlMetaData' as tableName, count(*) from absnew.DdlMetaData union all
select 'absold.DdlMetaData' as tableName, count(*) from absold.DdlMetaData union all
select 'absnew.GeoData' as tableName, count(*) from absnew.GeoData union all
select 'absold.GeoData' as tableName, count(*) from absold.GeoData union all
select 'absnew.Bank' as tableName, count(*) from absnew.Bank union all
select 'absold.Bank' as tableName, count(*) from absold.Bank union all
select 'absnew.Branch' as tableName, count(*) from absnew.Branch union all
select 'absold.Branch' as tableName, count(*) from absold.Branch union all
select 'absnew.Calendar' as tableName, count(*) from absnew.Calendar union all
select 'absold.Calendar' as tableName, count(*) from absold.Calendar union all
select 'absnew.CalendarDetails' as tableName, count(*) from absnew.CalendarDetails union all
select 'absold.CalendarDetails' as tableName, count(*) from absold.CalendarDetails union all
select 'absnew.SegmentDef' as tableName, count(*) from absnew.SegmentDef union all
select 'absold.SegmentDef' as tableName, count(*) from absold.SegmentDef union all
select 'absnew.SegmentItem' as tableName, count(*) from absnew.SegmentItem union all
select 'absold.SegmentItem' as tableName, count(*) from absold.SegmentItem union all
select 'absnew.ChargeModelDef' as tableName, count(*) from absnew.ChargeModelDef union all
select 'absold.ChargeModelDef' as tableName, count(*) from absold.ChargeModelDef union all
select 'absnew.ChargeModelItem' as tableName, count(*) from absnew.ChargeModelItem union all
select 'absold.ChargeModelItem' as tableName, count(*) from absold.ChargeModelItem union all
select 'absnew.PasswordPolicy' as tableName, count(*) from absnew.PasswordPolicy union all
select 'absold.PasswordPolicy' as tableName, count(*) from absold.PasswordPolicy union all
select 'absnew.PasswordHistory' as tableName, count(*) from absnew.PasswordHistory union all
select 'absold.PasswordHistory' as tableName, count(*) from absold.PasswordHistory union all
select 'absnew.AccountTransactionProfile' as tableName, count(*) from absnew.AccountTransactionProfile union all
select 'absold.AccountTransactionProfile' as tableName, count(*) from absold.AccountTransactionProfile union all
select 'absnew.OutletTransactionProfile' as tableName, count(*) from absnew.OutletTransactionProfile union all
select 'absold.OutletTransactionProfile' as tableName, count(*) from absold.OutletTransactionProfile union all
select 'absnew.ProductAccTransProfile' as tableName, count(*) from absnew.ProductAccTransProfile union all
select 'absold.ProductAccTransProfile' as tableName, count(*) from absold.ProductAccTransProfile union all
select 'absnew.DraftAgent' as tableName, count(*) from absnew.DraftAgent union all
select 'absold.AgentDraft' as tableName, count(*) from absold.AgentDraft union all
select 'absnew.Agent' as tableName, count(*) from absnew.Agent union all
select 'absold.Agent' as tableName, count(*) from absold.Agent union all
select 'absnew.AgentAccountDraft' as tableName, count(*) from absnew.AgentAccountDraft union all
select 'absold.AgentAccountDraft' as tableName, count(*) from absold.AgentAccountDraft union all
select 'absnew.AgentAccount' as tableName, count(*) from absnew.AgentAccount union all
select 'absold.AgentAccount' as tableName, count(*) from absold.AgentAccount union all
select 'absnew.DraftAgentServiceStaff' as tableName, count(*) from absnew.DraftAgentServiceStaff union all
select 'absold.AgentServiceStaffDraft' as tableName, count(*) from absold.AgentServiceStaffDraft union all
select 'absnew.AgentCategory' as tableName, count(*) from absnew.AgentCategory union all
select 'absold.AgentCategory' as tableName, count(*) from absold.AgentCategory union all
select 'absnew.OutletArea' as tableName, count(*) from absnew.OutletArea union all
select 'absold.OutletArea' as tableName, count(*) from absold.OutletArea union all
select 'absnew.OutletZone' as tableName, count(*) from absnew.OutletZone union all
select 'absold.OutletZone' as tableName, count(*) from absold.OutletZone union all
select 'absnew.DraftServicePoint' as tableName, count(*) from absnew.DraftServicePoint union all
select 'absold.ServicePointDraft' as tableName, count(*) from absold.ServicePointDraft union all
select 'absnew.ServicePoint' as tableName, count(*) from absnew.ServicePoint union all
select 'absold.ServicePoint' as tableName, count(*) from absold.ServicePoint union all
select 'absnew.FpDevice' as tableName, count(*) from absnew.FpDevice union all
select 'absold.ServiceTerminal' as tableName, count(*) from absold.ServiceTerminal union all
select 'absnew.ClientDevice' as tableName, count(*) from absnew.ClientDevice union all
select 'absold.ServiceTerminal' as tableName, count(*) from absold.ServiceTerminal union all
select 'absnew.PrinterDevice' as tableName, count(*) from absnew.PrinterDevice union all
select 'absold.ServiceTerminal' as tableName, count(*) from absold.ServiceTerminal union all
select 'absnew.CardDevice' as tableName, count(*) from absnew.CardDevice union all
select 'absold.ServiceTerminal' as tableName, count(*) from absold.ServiceTerminal union all
select 'absnew.ServiceTerminal' as tableName, count(*) from absnew.ServiceTerminal union all
select 'absold.ServiceTerminal' as tableName, count(*) from absold.ServiceTerminal union all
select 'absnew.AgentServiceStaff' as tableName, count(*) from absnew.AgentServiceStaff union all
select 'absold.AgentServiceStaff' as tableName, count(*) from absold.AgentServiceStaff union all
select 'absnew.person' as tableName, count(*) from absnew.person union all
select 'absold.customer' as tableName, count(*) from absold.customer union all
select 'absnew.customer' as tableName, count(*) from absnew.customer union all
select 'absold.customer' as tableName, count(*) from absold.customer union all
select 'absnew.Account' as tableName, count(*) from absnew.Account union all
select 'absold.Account' as tableName, count(*) from absold.Account union all
select 'absnew.CustomerAccount' as tableName, count(*) from absnew.CustomerAccount union all
select 'absold.CustomerAccount' as tableName, count(*) from absold.CustomerAccount union all
select 'absnew.CustomerQrCard' as tableName, count(*) from absnew.CustomerQrCard union all
select 'absold.CustomerQrCard' as tableName, count(*) from absold.CustomerQrCard union all
select 'absnew.PersonFingerprint' as tableName, count(*) from absnew.PersonFingerprint union all
select 'absold.fingerprint' as tableName, count(*) from absold.fingerprint union all
select 'absnew.personfingerprintlog' as tableName, count(*) from absnew.personfingerprintlog union all
select 'absold.fingerprintlog' as tableName, count(*) from absold.fingerprintlog union all
select 'absnew.SignatoryInfo' as tableName, count(*) from absnew.SignatoryInfo union all
select 'absold.SignatoryInfo' as tableName, count(*) from absold.SignatoryInfo union all
select 'absnew.AccountOperationInstruction' as tableName, count(*) from absnew.AccountOperationInstruction union all
select 'absold.SignatoryInfo' as tableName, count(*) from absold.SignatoryInfo union all
select 'absnew.FundTransferChargeModel' as tableName, count(*) from absnew.FundTransferChargeModel union all
select 'absold.FundTransferChargeModel' as tableName, count(*) from absold.FundTransferChargeModel union all
select 'absnew.BillType' as tableName, count(*) from absnew.BillType union all
select 'absold.BillType' as tableName, count(*) from absold.BillType union all
select 'absnew.UtilityCompany' as tableName, count(*) from absnew.UtilityCompany union all
select 'absold.UtilityCompany' as tableName, count(*) from absold.UtilityCompany union all
select 'absnew.CompanyZone' as tableName, count(*) from absnew.CompanyZone union all
select 'absold.CompanyZone' as tableName, count(*) from absold.CompanyZone union all
select 'absnew.ZoneAgent' as tableName, count(*) from absnew.ZoneAgent union all
select 'absold.ZoneAgent' as tableName, count(*) from absold.ZoneAgent union all
select 'absnew.ZoneBranch' as tableName, count(*) from absnew.ZoneBranch union all
select 'absold.ZoneBranch' as tableName, count(*) from absold.ZoneBranch union all
select 'absnew.BillCollection' as tableName, count(*) from absnew.BillCollection union all
select 'absold.BillCollection' as tableName, count(*) from absold.BillCollection union all
select 'absnew.RebChargeModel' as tableName, count(*) from absnew.RebChargeModel union all
select 'absold.RebChargeModel' as tableName, count(*) from absold.RebChargeModel union all
select 'absnew.GasBillCollection' as tableName, count(*) from absnew.GasBillCollection union all
select 'absold.GasBillCollection' as tableName, count(*) from absold.GasBillCollection union all
select 'absnew.GasJalalabadChargeModel' as tableName, count(*) from absnew.GasJalalabadChargeModel union all
select 'absold.GasJalalabadChargeModel' as tableName, count(*) from absold.GasJalalabadChargeModel union all
select 'absnew.ExchangeHouse' as tableName, count(*) from absnew.ExchangeHouse union all
select 'absold.ExchangeHouse' as tableName, count(*) from absold.ExchangeHouse union all
select 'absnew.Remittance' as tableName, count(*) from absnew.Remittance union all
select 'absold.Remittance' as tableName, count(*) from absold.Remittance;
