/*
This table to be used to store Bill Collection data
oid                                      : Bill Collection oid generated by system
csbRequestId                             : Request Id for csb system
cbsReferenceId                           : CBS response Id.
cbsVatReferenceId                        : Vat transaction cbs referance id
utilityCompanyOid                        : Oid of UtilityCompany table
companyZoneOid                           : Oid of CompanyZone table
zoneCode                                 : User will put from bill
entryDate                                : Entry Date
dueDate                                  : Bill payment last date
lastPaymentDate                          : After that date bill will not reccived
billPaymentMonth                         : Billing Month (ex. January, February etc.) 
customerName                             : Name of Customer
customerMobileNo                         : Customer Mobile Number
meterNo                                  : Meter No
usedUnit                                 : Unit have been used
billReferenceNumber                      : Reference number of bill
bookNumber                               : Book Number for bill
billAmount                               : Amount of bill
vatAmount                                : Vat amount on bill
meterRent                                : Meter Rent
transformerRent                          : Transformer Rent
penalty                                  : Penalty amount
othersFee                                : Other fees
lateFee                                  : Late payment fees
netBillAmount                            : Total bill amount
customerId                               : Type of bill
billTypeOid                              : Oid of BillType table
paymentType                              : Payment Type Cash (CASH) , Account (ACCOUNT) 
accountNumber                            :  Customer account number provided by utility company
debitAccount                             : From which account amount will go.
creditAccount                            : In which account amount will go.
revenueCount                             : Dose this bill have a stamp
billPic                                  : Bill receipt picture
submitterId                              : Wser id, who submitted this bill from mobile app
makerId                                  : User id, who made bill type
checkerId                                : User id, who checked bill type
approverId                               :  User id, who approved bill type
billStatus                               : Bill Status Make (BM) , Rejected (BR) , Active (A) , Checked (BC) , Submitted (AS) 
vatTransStatus                           : Vat transaction status
rejectionCause                           : Company rejection cause
agentOid                                 : Agent Id
servicePointOid                          : Service Point Id
branchOid                                : Branch Id
bankOid                                  : Bank Id
submissionDate                           : In which date bill submitted
transactionDate                          : In which date transaction completed
valueJson                                : Extra field will be in json formate
cutAgentCharge                           : Charge will be take from agent account
vatAccount                               : Vat account number
acutalAmount                             : Actual bill amount
monthNumber                              : In a bill how many number of month's bill taken
createdBy                                : Who (which login) created the record
createdOn                                : When the record was created
updatedBy                                : Who (which login) last updated the record
updatedOn                                : When the record was last updated
*/
create table                             BillCollection
(
oid                                      varchar(128)                                                not null,
csbRequestId                             varchar(128),
cbsReferenceId                           varchar(128),
cbsVatReferenceId                        varchar(128),
utilityCompanyOid                        varchar(128)                                                not null,
companyZoneOid                           varchar(128),
zoneCode                                 varchar(128),
entryDate                                date,
dueDate                                  date,
lastPaymentDate                          date,
billPaymentMonth                         varchar(256)                                                not null,
customerName                             varchar(256),
customerMobileNo                         varchar(64),
meterNo                                  varchar(64),
usedUnit                                 numeric(20,6),
billReferenceNumber                      varchar(128)                                                not null,
bookNumber                               varchar(128),
billAmount                               numeric(20,6),
vatAmount                                numeric(20,6),
meterRent                                numeric(20,6),
transformerRent                          numeric(20,6),
penalty                                  numeric(20,6),
othersFee                                numeric(20,6),
lateFee                                  numeric(20,6),
netBillAmount                            numeric(20,6)                                               not null,
customerId                               varchar(128),
billTypeOid                              varchar(128),
paymentType                              varchar(32)                                                 not null,
accountNumber                            varchar(64),
debitAccount                             varchar(64),
creditAccount                            varchar(64),
revenueCount                             numeric(20,6)                                               not null,
billPic                                  varchar(256),
submitterId                              varchar(128),
makerId                                  varchar(128),
checkerId                                varchar(128),
approverId                               varchar(128),
billStatus                               varchar(32),
vatTransStatus                           varchar(32),
rejectionCause                           text,
agentOid                                 varchar(128)                                                not null,
servicePointOid                          varchar(128)                                                not null,
branchOid                                varchar(128)                                                not null,
bankOid                                  varchar(128)                                                not null,
submissionDate                           date,
transactionDate                          date,
valueJson                                text,
cutAgentCharge                           varchar(32),
vatAccount                               varchar(128),
acutalAmount                             numeric(20,6),
monthNumber                              numeric(2,0),
createdBy                                varchar(128)                                                not null       default 'System',
createdOn                                timestamp                                                   not null       default current_timestamp,
updatedBy                                varchar(128),
updatedOn                                timestamp,
constraint                               pk_BillCollection                                           primary key    (oid),
constraint                               fk_utilityCompanyOid_BillCollection                         foreign key    (utilityCompanyOid)
                                                                                                     references     UtilityCompany(oid),
constraint                               fk_companyZoneOid_BillCollection                            foreign key    (companyZoneOid)
                                                                                                     references     CompanyZone(oid),
constraint                               fk_billTypeOid_BillCollection                               foreign key    (billTypeOid)
                                                                                                     references     BillType(oid),
constraint                               ck_paymentType_BillCollection                               check          (paymentType = 'Cash' or paymentType = 'Account' or paymentType = 'Cheque'),
constraint                               ck_billStatus_BillCollection                                check          (billStatus = 'Failed' or billStatus = 'OK' or billStatus = 'Pending'),
constraint                               ck_vatTransStatus_BillCollection                            check          (vatTransStatus = 'Failed' or vatTransStatus = 'OK' or vatTransStatus = 'Pending')
);


