/*
This table to be used to store Utility Provider Categories (ex. Gas, Electricity etc.) 
oid                                      : UtilityProviderClass oid generated by system
utilityProviderClassId                   : If user could provide any id
utilityProviderClassName                 : UtilityProviderClass name
description                              : Description for UtilityProviderClass
utilityProviderClassJson                 : JSON to keep necessary info
makerId                                  : User id, who made bill type
checkerId                                : User id, who checked bill type
approverId                               : User id, who approved bill type
status                                   : Status of this record
rejectionCause                           : Rejection cause
createdBy                                : Who (which login) created the record
createdOn                                : When the record was created
updatedBy                                : Who (which login) last updated the record
updatedOn                                : When the record was last updated
*/
create table                             UtilityProviderClass
(
oid                                      varchar(128)                                                not null,
utilityProviderClassId                   varchar(128),
utilityProviderClassName                 varchar(256),
description                              text,
utilityProviderClassJson                 text,
makerId                                  varchar(128),
checkerId                                varchar(128),
approverId                               varchar(128),
status                                   varchar(32)                                                 not null,
rejectionCause                           text,
createdBy                                varchar(128)                                                not null       default 'System',
createdOn                                timestamp                                                   not null       default current_timestamp,
updatedBy                                varchar(128),
updatedOn                                timestamp,
constraint                               pk_UtilityProviderClass                                     primary key    (oid),
constraint                               u_utilityProviderClassId_UtilityProviderClass               unique         (utilityProviderClassId),
constraint                               ck_status_UtilityProviderClass                              check          (status = 'Inactive' or status = 'Active' or status = 'ApplicationSubmitted' or status = 'BankMade' or status = 'BankApproved' or status = 'Cancel' or status = 'ApplicationRjected' or status = 'InEditable')
);

/*
This table to be used to store Utility Provider Companies
oid                                      : UtilityProvider oid generated by system
utilityProviderId                        : If user could want provide any id
utilityProviderName                      : UtilityProvider name
utilityProviderClassOid                  :  Utility Provider Class
description                              : Description for UtilityProvider
utilityProviderJson                      : Json to keep necessary info
makerId                                  : User id, who made bill type
checkerId                                : User id, who checked bill type
approverId                               : User id, who approved bill type
status                                   : Status of this record
rejectionCause                           : Rejection cause
createdBy                                : Who (which login) created the record
createdOn                                : When the record was created
updatedBy                                : Who (which login) last updated the record
updatedOn                                : When the record was last updated
*/
create table                             UtilityProvider
(
oid                                      varchar(128)                                                not null,
utilityProviderId                        varchar(128)                                                not null,
utilityProviderName                      varchar(256)                                                not null,
utilityProviderClassOid                  varchar(128)                                                not null,
description                              text,
utilityProviderJson                      text,
makerId                                  varchar(128),
checkerId                                varchar(128),
approverId                               varchar(128),
status                                   varchar(32)                                                 not null,
rejectionCause                           text,
createdBy                                varchar(128)                                                not null       default 'System',
createdOn                                timestamp                                                   not null       default current_timestamp,
updatedBy                                varchar(128),
updatedOn                                timestamp,
constraint                               pk_UtilityProvider                                          primary key    (oid),
constraint                               u_utilityProviderId_UtilityProvider                         unique         (utilityProviderId),
constraint                               fk_utilityProviderClassOid_UtilityProvider                  foreign key    (utilityProviderClassOid)
                                                                                                     references     UtilityProviderClass(oid),
constraint                               ck_status_UtilityProvider                                   check          (status = 'Inactive' or status = 'Active' or status = 'ApplicationSubmitted' or status = 'BankMade' or status = 'BankApproved' or status = 'Cancel' or status = 'ApplicationRjected' or status = 'InEditable')
);

/*
This table to be used to store Utility Provider Company Area
oid                                      :  UtilityProviderArea oid generated by system
utilityProviderAreaId                    : User could provide any id
utilityProviderAreaName                  : UtilityProviderArea name
utilityProviderOid                       : Utility Provider
utilityProviderClassOid                  : Utility Provider Class
description                              : Description for UtilityProviderArea
utilityProviderAreaJson                  : Json to keep necessary info
makerId                                  : User id, who made bill type
checkerId                                : User id, who checked bill type
approverId                               : User id, who approved bill type
status                                   : Status of this record
rejectionCause                           : Rejection cause
createdBy                                : Who (which login) created the record
createdOn                                : When the record was created
updatedBy                                : Who (which login) last updated the record
updatedOn                                : When the record was last updated
*/
create table                             UtilityProviderArea
(
oid                                      varchar(128)                                                not null,
utilityProviderAreaId                    varchar(128)                                                not null,
utilityProviderAreaName                  varchar(256)                                                not null,
utilityProviderOid                       varchar(128)                                                not null,
utilityProviderClassOid                  varchar(128)                                                not null,
description                              text,
utilityProviderAreaJson                  text,
makerId                                  varchar(128),
checkerId                                varchar(128),
approverId                               varchar(128),
status                                   varchar(32)                                                 not null,
rejectionCause                           text,
createdBy                                varchar(128)                                                not null       default 'System',
createdOn                                timestamp                                                   not null       default current_timestamp,
updatedBy                                varchar(128),
updatedOn                                timestamp,
constraint                               pk_UtilityProviderArea                                      primary key    (oid),
constraint                               u_utilityProviderAreaId_UtilityProviderArea                 unique         (utilityProviderAreaId),
constraint                               fk_utilityProviderOid_UtilityProviderArea                   foreign key    (utilityProviderOid)
                                                                                                     references     UtilityProvider(oid),
constraint                               fk_utilityProviderClassOid_UtilityProviderArea              foreign key    (utilityProviderClassOid)
                                                                                                     references     UtilityProviderClass(oid),
constraint                               ck_status_UtilityProviderArea                               check          (status = 'Inactive' or status = 'Active' or status = 'ApplicationSubmitted' or status = 'BankMade' or status = 'BankApproved' or status = 'Cancel' or status = 'ApplicationRjected' or status = 'InEditable')
);

/*
This table to be used to store Utility Provider Company Zones
oid                                      : UtilityProviderZone oid generated by system
utilityProviderZoneId                    : If user could want provide any id
utilityProviderZoneName                  : UtilityProviderZone name
utilityProviderAreaOid                   : Utility Provider Area
utilityProviderOid                       : Utility Provider
utilityProviderClassOid                  : Utility Provider Class
description                              : Description for UtilityProviderZone
utilityProviderZoneJson                  : Json to keep necessary info
utilityProviderZoneBankAccountNo         : Zone account number
makerId                                  : User id, who made bill type
checkerId                                : User id, who checked bill type
approverId                               : User id, who approved bill type
status                                   : Status of this record
rejectionCause                           : Rejection cause
createdBy                                : Who (which login) created the record
createdOn                                : When the record was created
updatedBy                                : Who (which login) last updated the record
updatedOn                                : When the record was last updated
*/
create table                             UtilityProviderZone
(
oid                                      varchar(128)                                                not null,
utilityProviderZoneId                    varchar(128)                                                not null,
utilityProviderZoneName                  varchar(256)                                                not null,
utilityProviderAreaOid                   varchar(128)                                                not null,
utilityProviderOid                       varchar(128)                                                not null,
utilityProviderClassOid                  varchar(128)                                                not null,
description                              text,
utilityProviderZoneJson                  text,
utilityProviderZoneBankAccountNo         varchar(64),
makerId                                  varchar(128),
checkerId                                varchar(128),
approverId                               varchar(128),
status                                   varchar(32)                                                 not null,
rejectionCause                           text,
createdBy                                varchar(128)                                                not null       default 'System',
createdOn                                timestamp                                                   not null       default current_timestamp,
updatedBy                                varchar(128),
updatedOn                                timestamp,
constraint                               pk_UtilityProviderZone                                      primary key    (oid),
constraint                               u_utilityProviderZoneId_UtilityProviderZone                 unique         (utilityProviderZoneId),
constraint                               fk_utilityProviderAreaOid_UtilityProviderZone               foreign key    (utilityProviderAreaOid)
                                                                                                     references     UtilityProviderArea(oid),
constraint                               fk_utilityProviderOid_UtilityProviderZone                   foreign key    (utilityProviderOid)
                                                                                                     references     UtilityProvider(oid),
constraint                               fk_utilityProviderClassOid_UtilityProviderZone              foreign key    (utilityProviderClassOid)
                                                                                                     references     UtilityProviderClass(oid),
constraint                               ck_status_UtilityProviderZone                               check          (status = 'Inactive' or status = 'Active' or status = 'ApplicationSubmitted' or status = 'BankMade' or status = 'BankApproved' or status = 'Cancel' or status = 'ApplicationRjected' or status = 'InEditable')
);


