/*
This table to be used to store Utility Customer Info
oid                                      : Utility Customer oid generated by system
utilityProviderClassOid                  : Oid of UtilityProviderClass table
utilityProviderOid                       : Oid of UtilityProvider table
utilityProviderAreaOid                   : Oid of UtilityProviderArea table
utilityProviderZoneOid                   : Oid of UtilityProviderZone table
utilityCustomerId                        : Id of UtilityProvider Customer
utilityCustomerType                      : Type of UtilityProvider Customer
customerName                             : Name of Customer
customerAddress                          : Address of Customer
customerMobileNo                         : Customer Mobile Number
customerBankAccountNo                    : Customer account number provided by utility company
customerDetailsJson                      : Customer details information
equipmentDetailsJson                     : Equipment details informantion
status                                   : Status showing active for active account, inactive for inactive account, ApplicationSubmitted for ApplicationSubmitted account, BankMade for BankMade account,  BankApproved for BankApproved account,  Cancel for Cancel account,  ApplicationRjected for ApplicationRjected account,  InEditable for InEditable account, of this record
createdBy                                : Who (which login) created the record
createdOn                                : When the record was created
updatedBy                                : Who (which login) last updated the record
updatedOn                                : When the record was last updated
*/
create table                             UtilityAccount
(
oid                                      varchar(128)                                                not null,
utilityProviderClassOid                  varchar(128),
utilityProviderOid                       varchar(128),
utilityProviderAreaOid                   varchar(128),
utilityProviderZoneOid                   varchar(128),
utilityCustomerId                        varchar(128),
utilityCustomerType                      varchar(32),
customerName                             varchar(256),
customerAddress                          text,
customerMobileNo                         varchar(64),
customerBankAccountNo                    varchar(64),
customerDetailsJson                      text,
equipmentDetailsJson                     text,
status                                   varchar(32),
createdBy                                varchar(128)                                                               default 'System',
createdOn                                timestamp                                                                  default current_timestamp,
updatedBy                                varchar(128),
updatedOn                                timestamp,
constraint                               pk_UtilityAccount                                           primary key    (oid),
constraint                               fk_utilityProviderClassOid_UtilityAccount                   foreign key    (utilityProviderClassOid)
                                                                                                     references     UtilityProviderClass(oid),
constraint                               fk_utilityProviderOid_UtilityAccount                        foreign key    (utilityProviderOid)
                                                                                                     references     UtilityProvider(oid),
constraint                               fk_utilityProviderAreaOid_UtilityAccount                    foreign key    (utilityProviderAreaOid)
                                                                                                     references     UtilityProviderArea(oid),
constraint                               fk_utilityProviderZoneOid_UtilityAccount                    foreign key    (utilityProviderZoneOid)
                                                                                                     references     UtilityProviderZone(oid),
constraint                               u_utilityCustomerId_UtilityAccount                          unique         (utilityCustomerId),
constraint                               ck_utilityCustomerType_UtilityAccount                       check          (utilityCustomerType = 'Unenrolled' or utilityCustomerType = 'Enrolled'),
constraint                               ck_status_UtilityAccount                                    check          (status = 'Inactive' or status = 'Active' or status = 'ApplicationSubmitted' or status = 'BankMade' or status = 'BankApproved' or status = 'Cancel' or status = 'ApplicationRjected' or status = 'InEditable')
);

/*
This table to be used to store UtilityBillDepositor
oid                                      : Utility Customer oid generated by system
utilityProviderClassOid                  : Oid of UtilityProviderClass table
utilityProviderOid                       : Oid of UtilityProvider table
utilityProviderAreaOid                   : Oid of UtilityProviderArea table
utilityProviderZoneOid                   : Oid of UtilityProviderZone table
utilityBillDepositorId                   : Id of bill depositor
billDepositorName                        : Bill depositor name
billDepositorMobileNo                    : Bill depositor mobile no
billDepositorBankAccountNo               : Customer account number provided by utility company
billDepositorDetailsJson                 : Bill depositor details in json
status                                   : Status showing active for active account, inactive for inactive account, ApplicationSubmitted for ApplicationSubmitted account, BankMade for BankMade account,  BankApproved for BankApproved account,  Cancel for Cancel account,  ApplicationRjected for ApplicationRjected account,  InEditable for InEditable account, of this record
createdBy                                : Who (which login) created the record
createdOn                                : When the record was created
updatedBy                                : Who (which login) last updated the record
updatedOn                                : When the record was last updated
*/
create table                             UtilityBillDepositor
(
oid                                      varchar(128)                                                not null,
utilityProviderClassOid                  varchar(128),
utilityProviderOid                       varchar(128),
utilityProviderAreaOid                   varchar(128),
utilityProviderZoneOid                   varchar(128),
utilityBillDepositorId                   varchar(128),
billDepositorName                        varchar(256),
billDepositorMobileNo                    varchar(64),
billDepositorBankAccountNo               varchar(64),
billDepositorDetailsJson                 text,
status                                   varchar(32),
createdBy                                varchar(128)                                                               default 'System',
createdOn                                timestamp                                                                  default current_timestamp,
updatedBy                                varchar(128),
updatedOn                                timestamp,
constraint                               pk_UtilityBillDepositor                                     primary key    (oid),
constraint                               fk_utilityProviderClassOid_UtilityBillDepositor             foreign key    (utilityProviderClassOid)
                                                                                                     references     UtilityProviderClass(oid),
constraint                               fk_utilityProviderOid_UtilityBillDepositor                  foreign key    (utilityProviderOid)
                                                                                                     references     UtilityProvider(oid),
constraint                               fk_utilityProviderAreaOid_UtilityBillDepositor              foreign key    (utilityProviderAreaOid)
                                                                                                     references     UtilityProviderArea(oid),
constraint                               fk_utilityProviderZoneOid_UtilityBillDepositor              foreign key    (utilityProviderZoneOid)
                                                                                                     references     UtilityProviderZone(oid),
constraint                               u_utilityBillDepositorId_UtilityBillDepositor               unique         (utilityBillDepositorId),
constraint                               u_billDepositorMobileNo_UtilityBillDepositor                unique         (billDepositorMobileNo),
constraint                               ck_status_UtilityBillDepositor                              check          (status = 'Inactive' or status = 'Active' or status = 'ApplicationSubmitted' or status = 'BankMade' or status = 'BankApproved' or status = 'Cancel' or status = 'ApplicationRjected' or status = 'InEditable')
);

/*
This table to be used to store UtilityBillDepositor
oid                                      : Utility Customer oid generated by system
utilityProviderClassId                   : Oid of UtilityProviderClass table
utilityProviderOid                       : Oid of UtilityProvider table
utilityProviderAreaOid                   : Oid of UtilityProviderArea table
utilityProviderZoneOid                   : Oid of UtilityProviderZone table
utilityBillDepositorOid                  : Bill depositor id
utilityCustomerOid                       : Id of UtilityProvider Customer
status                                   : Active showing for active status, inactive showing for inactive status  of this record
createdBy                                : Who (which login) created the record
createdOn                                : When the record was created
updatedBy                                : Who (which login) last updated the record
updatedOn                                : When the record was last updated
*/
create table                             UtilityAccountDepositorMap
(
oid                                      varchar(128)                                                not null,
utilityProviderClassId                   varchar(128),
utilityProviderOid                       varchar(128),
utilityProviderAreaOid                   varchar(128),
utilityProviderZoneOid                   varchar(128),
utilityBillDepositorOid                  varchar(128),
utilityCustomerOid                       varchar(128),
status                                   varchar(32),
createdBy                                varchar(128)                                                               default 'System',
createdOn                                timestamp                                                                  default current_timestamp,
updatedBy                                varchar(128),
updatedOn                                timestamp,
constraint                               pk_UtilityAccountDepositorMap                               primary key    (oid),
constraint                               fk_utilityProviderClassId_UtilityAccountDepositorMap        foreign key    (utilityProviderClassId)
                                                                                                     references     UtilityProviderClass(oid),
constraint                               fk_utilityProviderOid_UtilityAccountDepositorMap            foreign key    (utilityProviderOid)
                                                                                                     references     UtilityProvider(oid),
constraint                               fk_utilityProviderAreaOid_UtilityAccountDepositorMap        foreign key    (utilityProviderAreaOid)
                                                                                                     references     UtilityProviderArea(oid),
constraint                               fk_utilityProviderZoneOid_UtilityAccountDepositorMap        foreign key    (utilityProviderZoneOid)
                                                                                                     references     UtilityProviderZone(oid),
constraint                               fk_utilityBillDepositorOid_UtilityAccountDepositorMap       foreign key    (utilityBillDepositorOid)
                                                                                                     references     UtilityBillDepositor(oid),
constraint                               fk_utilityCustomerOid_UtilityAccountDepositorMap            foreign key    (utilityCustomerOid)
                                                                                                     references     UtilityAccount(oid),
constraint                               ck_status_UtilityAccountDepositorMap                        check          (status = 'Inactive' or status = 'Active' or status = 'ApplicationSubmitted' or status = 'BankMade' or status = 'BankApproved' or status = 'Cancel' or status = 'ApplicationRjected' or status = 'InEditable')
);


